---
title: "eda"
author: "Kate Colvin"
date: "2024-12-11"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gtsummary)
library(corrplot)
library(flextable)
library(gt)

```

## Data Cleaning 

Reading in + cleaning data

```{r}

score_df <- read_csv("Project_1_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(wkly_study_hours = 
           case_match(
             wkly_study_hours, 
             "< 5" ~ "< 5",
             "> 10" ~ "> 10", 
             "10-May" ~ "5-10"), 
         wkly_study_hours = factor(wkly_study_hours, c("< 5", "5-10", "> 10")))
  
```

Summary Table 1 (Demographics)

```{r}

table1 <- score_df %>% 
  select(-c(test_prep, wkly_study_hours, 
         math_score, reading_score, writing_score)) %>% 
  tbl_summary(
    by = gender,
    label = list("ethnic_group" ~ "Ethnic Group", 
                 "parent_educ" ~ "Parents' Education",
                 "lunch_type" ~ "Lunch Type", 
                 "parent_marital_status" ~ "Parents' Marital Status", 
                 "practice_sport" ~ "Practice Sport", 
                 "is_first_child" ~ "Oldest Child (Yes/No)", 
                 "nr_siblings" ~ "# Siblings", 
                 "transport_means" ~ "Transport Means"), 
    type = list(nr_siblings ~ "continuous"), 
    digits = list(all_continuous() ~ c(0))) %>% 
  bold_labels() %>% 
  modify_caption("Table 1. Summary of Student Demographic Variables (N=948)") %>% 
  add_overall() 
table1

# table1 %>%
#   as_gt() %>%
#   gtsave(filename = "table1.png")

```

Summary Table 2 (Academics)

```{r}

table2 <- score_df %>% 
  select(test_prep, wkly_study_hours, 
         math_score, reading_score, writing_score, gender) %>% 
  tbl_summary(
    by = gender,
    label = list("test_prep" ~ "Test Prep", 
                 "wkly_study_hours" ~ "Weekly Study Hours",
                 "math_score" ~ "Math Score", 
                 "reading_score" ~ "Reading Score", 
                 "writing_score" ~ "Writing Score")) %>% 
  bold_labels() %>% 
  modify_caption("Table 2. Summary of Student Academic Variables (N=948)") %>% 
  add_overall() 
table2

# table2 %>%
#   as_gt() %>%
#   gtsave(filename = "table2.png")

```


## Visualizations 

Plotting the overall distribution of scores, stratified by subject

```{r}

score_long_df <- score_df %>%  
  pivot_longer(cols = math_score:writing_score, 
               names_to = "subject", 
               values_to = "score")

score_dists_plot <- score_long_df %>% 
  ggplot(aes(x = score, fill = subject, color = subject)) +
  geom_density(alpha = 0.3, linewidth = 1) +
  labs(x = "Test Score", y = "Density", 
       title = "Figure 1: Distributions of Test Score by Subject")
score_dists_plot

ggsave("score_density.png", width = 7, height = 5)

# Test for differences 

score_test <- score_long_df %>% select(subject, score) %>% 
  tbl_summary(by = subject) %>% 
  add_overall() %>% 
  add_p()
score_test

```

Correlation between test scores 

```{r}

cor_matrix <- score_df %>% 
  select(math_score, reading_score, writing_score) %>% 
  cor()

corrplot(cor_matrix,  method = "color", 
         addCoef.col = "black", 
         tl.col = "black",      
         tl.srt = 45,
         order = 'hclust',
         diag = F)

```


```{r}

boxplots_study <- score_long_df %>% na.omit(wkly_study_hours) %>% 
  ggplot(aes(x = wkly_study_hours, y = score, fill = subject)) +
  geom_boxplot(alpha = 0.8) +
  labs(x = "Weekly Study Hours", y = "Test Score", 
       title = "Figure 2: Distributions of Test Scores by Subject and Weekly Study Hours")
boxplots_study

ggsave("study_boxplots.png",  width = 7, height = 5)

# Testing for differences in score distribution by study hour groups 

score_df %>% 
  select(test_prep, wkly_study_hours, 
         math_score, reading_score, writing_score) %>% 
  tbl_summary(
    by = wkly_study_hours,
    label = list("test_prep" ~ "Test Prep",
                 "math_score" ~ "Math Score", 
                 "reading_score" ~ "Reading Score", 
                 "writing_score" ~ "Writing Score")) %>% 
  bold_labels() %>% 
  add_overall() %>% 
  modify_caption("Table 3. Academic Variables by Time Spent Studying (N=911)") %>% 
  add_p()

```

